[package]
name = "roll"
version = "0.1.1"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
rand = "0.8.2"
colored = "2.0.0"
thiserror = "1.0.23"
hashbrown = "0.9.1"
