[package]
name = "roll"
version = "0.2.0"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
colored = "2.0.0"
either = "1.6.1"
expr = { path = '..\expr\' }
hashbrown = "0.10.0"
rand = "0.8.2"
