[package]
name = "exprng"
version = "0.2.3"
authors = ["J/A <archer884@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
expr = { path = '../expr' }
hashbrown = "0.12.1"
rand = "0.8.5"
smallvec = "1.8.0"
